### ISSUE TITLE
Mark a list dates

### ISSUE THREAD

**Issue by Rafelcf** [mateusz800/Expandable-Compose-Calendar#10]
Mateusz Budnik, is it possible to mark a list of dates with another color? Thanks for your time

**Comment by mateusz800** [comment]
<img width="208" alt="Screenshot 2024-05-24 at 21 04 32" src="https://github.com/mateusz800/Expandable-Compose-Calendar/assets/44299056/b58f8035-bcab-473a-883b-04257d243e33">

I've added possibility to define groups of dates and assign color to each of them. MR was merged to branch dev

**Comment by Rafelcf** [comment]
Thank you, I've been trying to mark a list of dates all day, please help me

data class Marked(var date : String, var group : String)

class MainActivity : ComponentActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContent {
            CalendarTheme {
                // A surface container using the 'background' color
from the theme
                Surface(
                    modifier = Modifier.fillMaxSize(),
                    color = MaterialTheme.colors.background
                ) {
                    Calendar()
                }
            }
        }
    }
}

@Composable
fun Calendar() {
    val currentDate = remember { mutableStateOf(LocalDate.now()) }
    val scrollState = rememberScrollState()
    val datesGroup = prepareExampleDateGroups()
    Column(Modifier.verticalScroll(scrollState)) {
        ExpandableCalendar(
            datesGroups = datesGroup,
            theme = calendarDefaultTheme.copy(
                dayShape = CircleShape,
                backgroundColor = Color.Black,
                selectedDayBackgroundColor = Color.White,
                dayValueTextColor = Color.White,
                selectedDayValueTextColor = Color.Black,
                headerTextColor = Color.White,
                weekDaysTextColor = Color.White
            ), onDayClick = {
                currentDate.value = it
            })
        Box(contentAlignment = Alignment.Center, modifier =
Modifier.fillMaxSize()) {
            Text("Selected date: ${currentDate.value}")
        }
    }
}

fun prepareExampleDateGroups(): List<DatesGroup> {
    val dates2 : ArrayList<Marked> = ArrayList()
    dates2.add(Marked("2024-05-21","xxx" ))
    dates2.add(Marked("2024-05-22", "xxx"))


    val markedDatesGroup1 = DatesGroup(dates = listOf(
        LocalDate.now().minusDays(1),
        LocalDate.now().minusDays(2),
        LocalDate.now().minusDays(5)
    ), color = Color.Cyan)
    val markedDatesGroup2 = DatesGroup(dates = listOf(
        LocalDate.now().plusDays(3),
        LocalDate.now().minusWeeks(1)
    ), color = Color.Yellow)
    println("fecha - " + LocalDate.now().minusDays(1))

    return listOf(markedDatesGroup1, markedDatesGroup2)
}
